// <auto-generated />
namespace AjourBT.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class QuestionSet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuestionSet));
        
        string IMigrationMetadata.Id
        {
            get { return "201501290847337_QuestionSet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
